version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak  # Link to PostgreSQL
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_IMPORT=/opt/keycloak/realm-export.json  # Import the realm configuration file (to be created later)
      - KEYCLOAK_LOGLEVEL=INFO
      - MINIO_URL=${S3_ENDPOINT}  # URL for MinIO service
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    command: ["start-dev"]
    ports:
      - "8080:8080"  # Expose Keycloak on port 8080
    depends_on:
      - postgres
      - minio
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data
    networks:
      - app-network
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # MinIO main endpoint
      - "9001:9001"  # MinIO web console
    volumes:
      - minio-data:/data  # Persistent storage for MinIO data
    networks:
      - app-network
    restart: always

  app:
    build:
      context: ./src  # Point to the directory with your application code
    container_name: app
    ports:
      - "5100:5000"  # Expose your app on port 5100
    depends_on:
      - keycloak
      - minio
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}  # Replace wi    th your actual Keycloak realm
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}  # Replac  e with your Keycloak client ID
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: {}
  minio-data: {}
